story4/urls.py
from django.contrib import admin
from django.urls import path, include
import webprofile.urls

urlpatterns = [
    path('', include(webprofile.urls, namespace = "webprofile")),
    path('admin/', admin.site.urls),
]

webprofile/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = "webprofile"
urlpatterns = [
    path('', profile, name="profile"),
    path('potofolio/', portofolio, name="portofolio"),
]

webprofile/models.py
from django.db import models

# Create your models here.

webprofile/views.py
from django.shortcuts import render

def profile(request):
    content = {'title' : "Zafira Binta"}
    return render(request, 'Tugas3.html', content)

def portofolio(request) :
    content = {'title' : "Foto Kucing"}
    return render(request, 'Tugas3-Foto.html', content)

webprofile/templates/Tugas3-Foto.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    
    <div id="kucing_1" class="card" style="width: 500px;">
        <img src="{% static 'kucing1.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“What greater gift than the love of a cat.” <br> – Charles Dickens</p>
        </div>
    </div> <br><br>

    <div id="kucing_2" class="card" style="width: 500px;">
        <img src="{% static 'kucing2.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“Time spent with a cat is never wasted.” <br> – Sigmund Freud</p>
        </div>
    </div> <br><br>

    <div id="kucing_3" class="card" style="width: 500px;">
        <img src="{% static 'kucing3.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“Cats are intended to teach us that not everything in nature has a purpose.” <br> – Garrison Keillor</p>
        </div>
    </div> <br><br>

    <div id="kucing_4" class="card" style="width: 500px;">
        <img src="{% static 'kucing4.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“Dogs come when they’re called; cats take a message and get back to you later.” <br> – Mary Bly</p>
        </div>
    </div> <br><br>

    <div id="kucing_5" class="card" style="width: 500px;">
        <img src="{% static 'kucing5.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“An ordinary kitten will ask more questions than any five year old.” <br> – Carl Van Vechten</p>
        </div>
    </div> <br><br>

    <div id="kucing_6" class="card" style="width: 500px;">
        <img src="{% static 'kucing6.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“One of my biggest fears is that I’m going to die alone in my home, and my cats will eat me because I am too dead to open their food cans.” <br> – Kelli Jae Baeli</p>
        </div>
    </div> <br><br>

    <div id="kucing_7" class="card" style="width: 500px;">
        <img src="{% static 'kucing7.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">"No matter how much the cats fight, there always seem to be plenty of kittens." <br> – Abraham Lincoln</p>
        </div>
    </div> <br><br>

    <div id="kucing_8" class="card" style="width: 500px;">
        <img src="{% static 'kucing8.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“Cats have it all – admiration, an endless sleep, and company only when they want it.” <br> – Rod McKuen</p>
        </div>
    </div> <br><br>

    <div id="kucing_9" class="card" style="width: 500px;">
        <img src="{% static 'kucing9.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px"> 
        <div class="card-body">
            <p class="card-text">"Curiosity killed the cat, and satisfaction brought it back." <br> – Eugene O’Neill</p>
        </div>
    </div> <br><br>

    <div id="kucing_10" class="card" style="width: 500px;">
        <img src="{% static 'kucing10.jpg' %}" class="card-img-top" alt="kucing" height="500px" width="500px">
        <div class="card-body">
            <p class="card-text">“Smelly cat. Smelly cat. What are they feeding you?” <br> – Phoebe Buffay</p>
        </div>
    </div>
{% endblock %}

webprofile/templates/Tugas3.html
    {% extends 'base.html' %}
    {% load staticfiles %}
    
    {% block content %}
    <div class="single_page">
        <ul class="kumpulan_pages" style="display: block" border="0">
            <li class="beranda">
                <h3 class="teks_beranda">"Halo! Saya</h3> <br>
                <h1 class="teks_beranda" id="nama_beranda">Zafira Binta,</h1>
            </li>

            <li class="biodata">
                <div id="foto_profil">
                    <img src="{% static 'foto_profil.jpg' %}" alt="zafira" height="400px" width="300px">
                </div>

                <div>
                    <p id="teks_biodata">seorang mahasiswi Universitas Indonesia jurusan Ilmu Komputer 
                        angkatan 2018 yang sangat menyukai fotografi, kucing, dan cokelat."        
                    </p>
                </div>
                <div>
                    <table class="table_biodata" border="0">
                        <tr>
                            <td class="icon"><img src="{% static 'icon_location.png' %}" height=60 width=60></img></td>
                            <td class="teks_table_biodata">Jakarta, Indonesia</td>
                        </tr>
                              
                        <tr>
                            <td class="icon"><img src="{% static 'icon_calendar.png' %}" height=60 width=60></img></td>
                            <td class="teks_table_biodata">2 Mei 2000</td>
                        </tr>
                        
                        <tr>
                            <td class="icon"><img src="{% static 'icon_email.png' %}" height=60 width=60></img></td>
                            <td class="teks_table_biodata">zafira.binta@ui.ac.id</td>
                        </tr>	

                        <tr>
                            <td class="icon"><img src="{% static 'icon_npm.png' %}" height=60 width=60></img></td>
                            <td class="teks_table_biodata">1806205155</td>
                        </tr>
                    </table>
                </div>
                

            </li>

            <li class="pendidikan">
                <div class="batas_judul" id="batas_judul_muda">
                    <h3>Perjalanan saya menuntut ilmu</h3>
                </div>
                <div id="sd">
                    <div class="judul_teks">
                        <h1 class="judul_pendidikan" id="judul_pendidikan_sd">SDN 10<br>Pesanggrahan</h1>
                        <p class="teks_pendidikan" id="teks_pendidikan_sd">Saya bersekolah di SDN 10 Pesanggrahan pada tahun 2006 dan lulus pada tahun 2012</p>
                    </div>
                </div>

                <div id="smp">
                    <div class="judul_teks">
                        <h1 class="judul_pendidikan" id="judul_pendidikan_smp">SMPN 177<br>Jakarta</h1>
                        <p class="teks_pendidikan" id="teks_pendidikan_smp">Saya melanjutkan pendidikan ke SMPN 177 Jakarta pada tahun 2012 hingga tahun 2015</p>
                    </div>
                </div>

                <div id="sma">
                    <div class="judul_teks">
                        <h1 class="judul_pendidikan" id="judul_pendidikan_sma">SMAN 8<br>Jakarta</h1>
                        <p class="teks_pendidikan" id="teks_pendidikan_sma">Selanjutnya saya menuntut ilmu di SMAN 8 Jakarta pada tahun 2015 sampai 2018</p>
                    </div>  
                </div>

                <div id="kuliah">
                    <div class="judul_teks">
                        <h1 class="judul_pendidikan" id="judul_pendidikan_kuliah">Fasilkom<br>UI</h1>
                        <p class="teks_pendidikan" id="teks_pendidikan_kuliah">Sekarang saya adalah mahasiswi tahun kedua di Fakultas Ilmu Komputer Universitas Indonesia </p>
                    </div>
                </div>

            </li>

            <li class="pengalaman">
                <div class="batas_judul">
                    <h3>Pengalaman yang pernah saya dapatkan</h3>
                </div>

                <div id="bem">
                    <img id="logo_bem" src="{% static 'logo_bem.png' %}" alt="BEM FASILKOM UI" height="500" width="416.6666">
                    <h1 id="judul_bem">BEM FASILKOM UI<br>2019</h1>
                    <p id="teks_bem">Sejak kuliah semester 2 saya bergabung dalam BEM Fasilkom UI sebagai staff Media BEM Fasilkom UI 2019 dan menjadi media partner Adkesma BEM Fasilkom UI. Saya membuat poster sesuai permintaan Biro Adkesma.</p>
                </div>

                <div id="fuki">
                    <img id="logo_fuki" src="{% static 'logo_fuki.png' %}" alt="FUKI FASILKOM UI" height="500" width="416.6666">
                    <h1 id="judul_fuki">FUKI FASILKOM UI <br> 2019</h1>
                    <p id="teks_fuki">Saya bergabung dengan FUKI Fasilkom UI sejak semester 2 sebagai staff Biro Humas FUKI Fasilkom UI 2019 dan menjadi humas partner Departemen Pengabdian Masyarakat FUKI Fasilkom UI. Saya membuat <em>broadcast</em> sesuai permintaan Departemen Pengmas. </p>
                </div>
            </li>

            <li class="portofolio">
                <div class="batas_judul">
                    <h3>Hal-hal yang saya sukai</h3>
                </div>

                <div>
                    <p id="teks_portofolio">Ini adalah hasil dari penggabungan dua hal yang saya sukai, fotografi dan kucing</p>
                </div>

                <div class="foto">
                    <table class="foto_kucing">
                        <tr>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_1"><img class="foto_kucing_img" src="{% static 'kucing1.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_2"><img class="foto_kucing_img" src="{% static 'kucing2.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_3"><img class="foto_kucing_img" src="{% static 'kucing3.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_4"><img class="foto_kucing_img" src="{% static 'kucing4.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_5"><img class="foto_kucing_img" src="{% static 'kucing5.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                        </tr>

                        <tr>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_6"><img class="foto_kucing_img" src="{% static 'kucing6.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_7"><img class="foto_kucing_img" src="{% static 'kucing7.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_8"><img class="foto_kucing_img" src="{% static 'kucing8.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_9"><img class="foto_kucing_img" src="{% static 'kucing9.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                            <td class="foto_kucing_td"><a href="{% url 'webprofile:portofolio' %}#kucing_10"><img class="foto_kucing_img" src="{% static 'kucing10.jpg' %}" alt="kucing" height="250px" width="250px"></a></td>
                        </tr>
                    </table>
                   

            </li>

            <li class="kontak">
                <div class="batas_judul">
                    <h3>Cari tahu lebih lanjut tentang saya!</h3>
                </div>

                <div>
                    <table class="table_link" align="center" border="0">
                        <tr><td><a href="https://id.linkedin.com/in/zafira-binta-feliandra-a47655191">LinkedIn</a></td></tr>
                        <tr><td><a href="http://line.me/ti/p/zafirabinta">LINE</a></td></tr>
                        <tr><td><a href="https://www.facebook.com/zafirabinta">Facebook</a></td></tr>
                        <tr><td><a href="https://instagram.com/zafirabinta">Instagram</a></td></tr>
                        <tr><td><a href="https://twitter.com/__zzaf">Twitter</a></td></tr>                                                      
                    </table>
                </div>
            </li>
        </ul>
    </div>
    {% endblock %}

webprofile/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'webprofile:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webprofile:portofolio' %}">Portofolio</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}

</body>
</html>